title: My Jekyll Blog
description: A simple Jekyll blog hosted on GitHub Pages
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol, e.g. http://example.com
github_username: username
permalink: /:year/:month/:day/:title/
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  
# Build settings
markdown: kramdown 